/**
 * The spider who stands on every screen.
 *
 * Looking at what preschool alphabet apps actually do, the character is not
 * decoration. It is the narrator: it points at the thing you are supposed to
 * look at, it waits while you think, and it celebrates when you get it right.
 * A screen with a character on it is a scene somebody is in; the same screen
 * without one is a form.
 *
 * ## Poses, not a sprite sheet
 *
 * The art is four drawn poses — idle, point, cheer, blink — generated by
 * tools/make-mascot.mjs and committed. There is no rig and no per-limb
 * animation, because the thing an image model cannot do is draw the same
 * character eight times consistently enough to play back as frames. It can draw
 * the same character in a different pose, so the app swaps between whole poses
 * and gets its liveliness from tweens on the sprite: a bob, a hop, a wobble.
 *
 * That constraint decides the shape of this module. A pose swap is instant and
 * a tween is continuous, so anything that needs to look smooth has to be the
 * tween, and anything that changes shape has to be the swap.
 *
 * The four images are drawn to line up with each other — same size, feet on the
 * same line — which is done at generation time rather than here. See the
 * alignment pass in tools/make-mascot.mjs; without it the spider visibly jolts
 * every time it blinks.
 *
 * The whole set is 133 KB, which the service worker precaches with everything
 * else, so it still works offline.
 */

const BASE = import.meta.env.BASE_URL ?? '/';

/** @type {const} */
const POSES = ['idle', 'point', 'cheer', 'blink'];

/** How tall the sprite is drawn when nobody asks for a size. */
const DEFAULT_HEIGHT = 230;

const textureKey = (pose) => `mascot:${pose}`;

/**
 * Queues the mascot's art. Call from a scene's `preload()`.
 *
 * Loaded once up front rather than per screen: it is on every screen, so there
 * is nothing to defer, and a character that pops in a frame late on each scene
 * change looks broken.
 */
export function queueMascot(scene) {
  for (const pose of POSES) {
    const key = textureKey(pose);
    if (scene.textures.exists(key)) continue;
    scene.load.image(key, `${BASE}images/mascot/${pose}.webp`);
  }
}

/** Whether the art actually loaded. */
function available(scene) {
  return POSES.every((pose) => scene.textures.exists(textureKey(pose)));
}

/**
 * A stand-in with the same methods, for when the art is missing.
 *
 * Returned rather than throwing, and rather than letting Phaser draw its green
 * missing-texture square: every screen calls these methods, and a broken image
 * path should cost the app its character, not its games.
 */
function noMascot(scene, x, y) {
  const empty = scene.add.container(x, y);
  empty.idle = () => {};
  empty.point = () => {};
  empty.cheer = () => {};
  empty.wonder = () => {};
  return empty;
}

/**
 * Adds the spider to a scene.
 *
 * The returned container carries the poses. They are all safe to call at any
 * time and safe to call twice — a scene should be able to say "point at this"
 * on every round without tracking what the character was doing before.
 *
 * @param {Phaser.Scene} scene
 * @param {number} x
 * @param {number} y the ground it stands on, not its centre.
 * @param {{height?: number, depth?: number}} [options]
 */
export function addMascot(scene, x, y, options = {}) {
  const { height = DEFAULT_HEIGHT, depth = 4 } = options;
  if (!available(scene)) {
    console.warn('mascot: art not loaded; call queueMascot() in preload()');
    return noMascot(scene, x, y);
  }

  const root = scene.add.container(x, y).setDepth(depth);

  // Origin at the bottom centre, so `y` is the ground the spider stands on and
  // a wobble pivots at its feet rather than around its middle. The art is
  // square and drawn with the feet on the bottom edge, which is what makes
  // that work without any per-pose offsets here.
  const sprites = Object.fromEntries(
    POSES.map((pose) => {
      const sprite = scene.add.image(0, 0, textureKey(pose));
      sprite.setOrigin(0.5, 1).setDisplaySize(height, height).setVisible(false);
      root.add(sprite);
      return [pose, sprite];
    })
  );

  let current = 'idle';
  const show = (pose) => {
    sprites[current].setVisible(false);
    sprites[pose].setVisible(true);
    current = pose;
  };
  show('idle');

  /** Tweens owned by the current pose, stopped when the next one starts. */
  let poseTweens = [];
  const own = (tween) => {
    poseTweens.push(tween);
    return tween;
  };
  const clearPose = () => {
    for (const tween of poseTweens) tween.stop();
    poseTweens = [];
    root.setScale(1);
    root.setAngle(0);
    root.y = y;
  };

  /**
   * Blinking is a pose swap for a tenth of a second.
   *
   * Only while idle: the blink art has the legs down, so blinking mid-point
   * would drop the arm the spider is pointing with and put it back.
   */
  const blinkTimer = scene.time.addEvent({
    delay: 3400,
    loop: true,
    callback: () => {
      if (current !== 'idle') return;
      show('blink');
      scene.time.delayedCall(130, () => {
        if (current === 'blink') show('idle');
      });
    },
  });

  /** A slow breath. Squashing about the feet keeps them planted. */
  const breathe = (amount = 0.03, duration = 1500) =>
    own(
      scene.tweens.add({
        targets: root,
        scaleY: 1 + amount,
        scaleX: 1 - amount * 0.5,
        duration,
        yoyo: true,
        repeat: -1,
        ease: 'Sine.easeInOut',
      })
    );

  /** Standing about. What it does most of the time. */
  root.idle = () => {
    clearPose();
    show('idle');
    breathe();
  };

  /**
   * An arm out towards the answers, which is its whole job during a question:
   * it says "look over there" without a word of text.
   */
  root.point = () => {
    clearPose();
    show('point');
    breathe(0.02, 900);
  };

  /** Both arms up and a hop. Returns to idle on its own. */
  root.cheer = () => {
    clearPose();
    show('cheer');
    own(
      scene.tweens.add({
        targets: root,
        y: y - height * 0.14,
        duration: 260,
        yoyo: true,
        repeat: 2,
        ease: 'Quad.easeOut',
      })
    );
    own(
      scene.tweens.add({
        targets: root,
        angle: { from: -5, to: 5 },
        duration: 260,
        yoyo: true,
        repeat: 4,
        ease: 'Sine.easeInOut',
        onComplete: () => root.idle(),
      })
    );
  };

  /** A puzzled wobble. Never a frown: there are no fail states in this app. */
  root.wonder = () => {
    scene.tweens.add({
      targets: root,
      angle: { from: -9, to: 9 },
      duration: 150,
      yoyo: true,
      repeat: 2,
      ease: 'Sine.easeInOut',
      onComplete: () => root.setAngle(0),
    });
  };

  scene.events.once('shutdown', () => {
    blinkTimer.remove();
    clearPose();
  });

  root.idle();
  return root;
}

/**
 * The spider at the size and spot every game screen puts it: standing on the
 * ground at the left, clear of a row of answers across the middle.
 *
 * Centralised so it is in the same place from screen to screen. A character
 * that jumps around between activities stops reading as the same character.
 */
export function addStageMascot(scene, options = {}) {
  return addMascot(scene, 122, 664, { height: 236, ...options });
}
