/* The two rules worth having, and nothing else. */

import js from '@eslint/js';

/* Browser globals the app uses. */
const BROWSER = {
  window: 'readonly',
  document: 'readonly',
  navigator: 'readonly',
  console: 'readonly',
  fetch: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  performance: 'readonly',
  location: 'readonly',
  localStorage: 'readonly',
  indexedDB: 'readonly',
  Image: 'readonly',
  Blob: 'readonly',
  File: 'readonly',
  FileReader: 'readonly',
  URL: 'readonly',
  Audio: 'readonly',
  AudioContext: 'readonly',
  AudioBufferSourceNode: 'readonly',
  MediaStreamAudioDestinationNode: 'readonly',
  OfflineAudioContext: 'readonly',
  MediaRecorder: 'readonly',
  MediaStream: 'readonly',
  DecompressionStream: 'readonly',
  CompressionStream: 'readonly',
  Response: 'readonly',
  Request: 'readonly',
  Headers: 'readonly',
  FormData: 'readonly',
  CustomEvent: 'readonly',
  Event: 'readonly',
  HTMLElement: 'readonly',
  getComputedStyle: 'readonly',
  matchMedia: 'readonly',
  btoa: 'readonly',
  atob: 'readonly',
  structuredClone: 'readonly',
  crypto: 'readonly',
  self: 'readonly',
  alert: 'readonly',
  requestIdleCallback: 'readonly',
  Path2D: 'readonly',
  DOMPoint: 'readonly',
  screen: 'readonly',
  TextEncoder: 'readonly',
  TextDecoder: 'readonly',
  getSelection: 'readonly',
  caches: 'readonly',
  MutationObserver: 'readonly',
  Element: 'readonly',
  ErrorEvent: 'readonly',
};

const NODE = {
  process: 'readonly',
  Buffer: 'readonly',
  console: 'readonly',
  fetch: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  URL: 'readonly',
  TextEncoder: 'readonly',
  TextDecoder: 'readonly',
  Blob: 'readonly',
  File: 'readonly',
  FormData: 'readonly',
  Response: 'readonly',
  Request: 'readonly',
  Headers: 'readonly',
  DecompressionStream: 'readonly',
  CompressionStream: 'readonly',
  structuredClone: 'readonly',
  crypto: 'readonly',
  __dirname: 'readonly',
};

const rules = {
  'no-undef': 'error',
  'no-new-func': 'error',
  // Arguments are exempt.
  'no-unused-vars': [
    'error',
    { args: 'none', caughtErrors: 'none', ignoreRestSiblings: true },
  ],
};

export default [
  { ignores: ['dist/**', 'node_modules/**', 'public/**', 'content/**'] },
  js.configs.recommended,
  {
    files: ['src/**/*.js'],
    languageOptions: { ecmaVersion: 2024, sourceType: 'module', globals: BROWSER },
    rules,
  },
  {
    // The recording studio is a browser page served by a Node script.
    files: ['tools/**/*.{js,mjs}', 'tests/**/*.mjs', '*.js'],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'module',
      globals: { ...BROWSER, ...NODE },
    },
    rules,
  },
];
